import "dotenv/config";
import mongoose from "mongoose";
import { Recipe } from "../db/recipes.js";

const recipes = [
  // --- Café da Manhã (10) ---
  {
    name: "Tapioca com Ovo e Queijo",
    description: "Tapioca recheada com ovo mexido e queijo branco",
    ingredients: [
      { name: "Goma de tapioca", amount: "3 colheres" },
      { name: "Ovo", amount: "2 unidades" },
      { name: "Queijo branco", amount: "30g" },
    ],
    macros: { calories: 320, protein: 22, carbs: 35, fat: 12 },
    tags: ["breakfast"],
    prepTime: 10,
    difficulty: "easy",
    servings: 1,
  },
  {
    name: "Açaí com Granola e Banana",
    description: "Bowl de açaí com granola caseira e banana fatiada",
    ingredients: [
      { name: "Polpa de açaí", amount: "200ml" },
      { name: "Granola", amount: "30g" },
      { name: "Banana", amount: "1 unidade" },
    ],
    macros: { calories: 380, protein: 8, carbs: 62, fat: 12 },
    tags: ["breakfast", "snack"],
    prepTime: 5,
    difficulty: "easy",
    servings: 1,
  },
  {
    name: "Omelete de Espinafre",
    description: "Omelete com espinafre, tomate cereja e queijo cottage",
    ingredients: [
      { name: "Ovo", amount: "3 unidades" },
      { name: "Espinafre", amount: "1 xícara" },
      { name: "Tomate cereja", amount: "5 unidades" },
      { name: "Queijo cottage", amount: "2 colheres" },
    ],
    macros: { calories: 280, protein: 24, carbs: 6, fat: 18 },
    tags: ["breakfast"],
    prepTime: 10,
    difficulty: "easy",
    servings: 1,
  },
  {
    name: "Pão Integral com Abacate",
    description: "Torrada integral com pasta de abacate e ovo pochê",
    ingredients: [
      { name: "Pão integral", amount: "2 fatias" },
      { name: "Abacate", amount: "½ unidade" },
      { name: "Ovo", amount: "1 unidade" },
      { name: "Sal e limão", amount: "a gosto" },
    ],
    macros: { calories: 350, protein: 14, carbs: 32, fat: 20 },
    tags: ["breakfast"],
    prepTime: 10,
    difficulty: "easy",
    servings: 1,
  },
  {
    name: "Mingau de Aveia com Frutas",
    description: "Mingau de aveia com leite, mel e frutas vermelhas",
    ingredients: [
      { name: "Aveia em flocos", amount: "4 colheres" },
      { name: "Leite", amount: "200ml" },
      { name: "Mel", amount: "1 colher" },
      { name: "Frutas vermelhas", amount: "½ xícara" },
    ],
    macros: { calories: 310, protein: 12, carbs: 48, fat: 8 },
    tags: ["breakfast"],
    prepTime: 8,
    difficulty: "easy",
    servings: 1,
  },
  {
    name: "Smoothie Verde Energizante",
    description: "Smoothie de banana, espinafre e pasta de amendoim",
    ingredients: [
      { name: "Banana", amount: "1 unidade" },
      { name: "Espinafre", amount: "1 xícara" },
      { name: "Pasta de amendoim", amount: "1 colher" },
      { name: "Leite", amount: "200ml" },
    ],
    macros: { calories: 290, protein: 12, carbs: 38, fat: 12 },
    tags: ["breakfast", "snack"],
    prepTime: 5,
    difficulty: "easy",
    servings: 1,
  },
  {
    name: "Crepioca de Frango",
    description: "Crepioca recheada com frango desfiado e requeijão",
    ingredients: [
      { name: "Ovo", amount: "1 unidade" },
      { name: "Goma de tapioca", amount: "2 colheres" },
      { name: "Frango desfiado", amount: "50g" },
      { name: "Requeijão", amount: "1 colher" },
    ],
    macros: { calories: 290, protein: 24, carbs: 20, fat: 13 },
    tags: ["breakfast"],
    prepTime: 10,
    difficulty: "easy",
    servings: 1,
  },
  {
    name: "Iogurte com Chia e Manga",
    description: "Iogurte natural com chia e cubos de manga",
    ingredients: [
      { name: "Iogurte natural", amount: "170g" },
      { name: "Chia", amount: "1 colher" },
      { name: "Manga", amount: "½ unidade" },
    ],
    macros: { calories: 220, protein: 10, carbs: 30, fat: 7 },
    tags: ["breakfast", "snack"],
    prepTime: 3,
    difficulty: "easy",
    servings: 1,
  },
  {
    name: "Panqueca de Banana e Aveia",
    description: "Panqueca fit sem farinha com banana e aveia",
    ingredients: [
      { name: "Banana", amount: "1 unidade" },
      { name: "Ovo", amount: "2 unidades" },
      { name: "Aveia", amount: "3 colheres" },
    ],
    macros: { calories: 280, protein: 16, carbs: 35, fat: 10 },
    tags: ["breakfast"],
    prepTime: 12,
    difficulty: "easy",
    servings: 1,
  },
  {
    name: "Cuscuz com Ovo e Manteiga",
    description: "Cuscuz nordestino com ovo frito e manteiga",
    ingredients: [
      { name: "Flocos de milho", amount: "½ xícara" },
      { name: "Ovo", amount: "1 unidade" },
      { name: "Manteiga", amount: "1 colher chá" },
    ],
    macros: { calories: 310, protein: 12, carbs: 40, fat: 13 },
    tags: ["breakfast"],
    prepTime: 15,
    difficulty: "easy",
    servings: 1,
  },

  // --- Almoço (15) ---
  {
    name: "Frango Grelhado com Arroz Integral",
    description: "Peito de frango grelhado com arroz integral e brócolis",
    ingredients: [
      { name: "Peito de frango", amount: "150g" },
      { name: "Arroz integral", amount: "½ xícara" },
      { name: "Brócolis", amount: "1 xícara" },
    ],
    macros: { calories: 420, protein: 42, carbs: 38, fat: 10 },
    tags: ["lunch", "post_workout"],
    prepTime: 25,
    difficulty: "easy",
    servings: 1,
  },
  {
    name: "Salmão com Batata Doce",
    description: "Filé de salmão assado com batata doce e aspargos",
    ingredients: [
      { name: "Salmão", amount: "150g" },
      { name: "Batata doce", amount: "1 média" },
      { name: "Aspargos", amount: "6 talos" },
    ],
    macros: { calories: 480, protein: 38, carbs: 40, fat: 18 },
    tags: ["lunch", "dinner"],
    prepTime: 30,
    difficulty: "medium",
    servings: 1,
  },
  {
    name: "Bowl de Quinoa com Legumes",
    description: "Bowl de quinoa com grão-de-bico, abóbora e rúcula",
    ingredients: [
      { name: "Quinoa", amount: "½ xícara" },
      { name: "Grão-de-bico", amount: "½ xícara" },
      { name: "Abóbora", amount: "100g" },
      { name: "Rúcula", amount: "1 xícara" },
    ],
    macros: { calories: 380, protein: 18, carbs: 52, fat: 10 },
    tags: ["lunch"],
    prepTime: 25,
    difficulty: "medium",
    servings: 1,
  },
  {
    name: "Feijoada Light",
    description: "Feijoada sem partes gordas, com arroz e couve",
    ingredients: [
      { name: "Feijão preto", amount: "1 concha" },
      { name: "Lombo suíno", amount: "80g" },
      { name: "Arroz", amount: "3 colheres" },
      { name: "Couve refogada", amount: "1 xícara" },
    ],
    macros: { calories: 450, protein: 30, carbs: 50, fat: 14 },
    tags: ["lunch"],
    prepTime: 40,
    difficulty: "medium",
    servings: 1,
  },
  {
    name: "Strogonoff de Frango Fit",
    description: "Strogonoff com iogurte em vez de creme de leite",
    ingredients: [
      { name: "Peito de frango", amount: "150g" },
      { name: "Iogurte natural", amount: "3 colheres" },
      { name: "Champignon", amount: "50g" },
      { name: "Arroz integral", amount: "½ xícara" },
    ],
    macros: { calories: 400, protein: 38, carbs: 35, fat: 12 },
    tags: ["lunch", "dinner"],
    prepTime: 25,
    difficulty: "medium",
    servings: 1,
  },
  {
    name: "Escondidinho de Carne Moída",
    description: "Purê de mandioquinha com carne moída magra",
    ingredients: [
      { name: "Mandioquinha", amount: "200g" },
      { name: "Carne moída magra", amount: "120g" },
      { name: "Cebola", amount: "½ unidade" },
    ],
    macros: { calories: 380, protein: 28, carbs: 40, fat: 12 },
    tags: ["lunch", "dinner"],
    prepTime: 35,
    difficulty: "medium",
    servings: 1,
  },
  {
    name: "Salada Caesar com Frango",
    description: "Salada com alface romana, frango grelhado e croutons",
    ingredients: [
      { name: "Alface romana", amount: "2 xícaras" },
      { name: "Peito de frango", amount: "120g" },
      { name: "Parmesão", amount: "20g" },
      { name: "Croutons integrais", amount: "2 colheres" },
    ],
    macros: { calories: 340, protein: 32, carbs: 18, fat: 16 },
    tags: ["lunch"],
    prepTime: 15,
    difficulty: "easy",
    servings: 1,
  },
  {
    name: "Wrap Integral de Atum",
    description: "Wrap com atum, alface, tomate e iogurte",
    ingredients: [
      { name: "Tortilha integral", amount: "1 unidade" },
      { name: "Atum em água", amount: "1 lata" },
      { name: "Alface", amount: "2 folhas" },
      { name: "Tomate", amount: "3 fatias" },
    ],
    macros: { calories: 310, protein: 28, carbs: 30, fat: 8 },
    tags: ["lunch", "snack"],
    prepTime: 10,
    difficulty: "easy",
    servings: 1,
  },
  {
    name: "Moqueca de Peixe",
    description: "Moqueca baiana com peixe branco, leite de coco e dendê",
    ingredients: [
      { name: "Peixe branco", amount: "150g" },
      { name: "Leite de coco", amount: "100ml" },
      { name: "Pimentão", amount: "½ unidade" },
      { name: "Azeite de dendê", amount: "1 colher" },
    ],
    macros: { calories: 380, protein: 30, carbs: 12, fat: 24 },
    tags: ["lunch", "dinner"],
    prepTime: 35,
    difficulty: "medium",
    servings: 1,
  },
  {
    name: "Arroz com Lentilha e Legumes",
    description: "Arroz integral com lentilha, cenoura e abobrinha",
    ingredients: [
      { name: "Arroz integral", amount: "½ xícara" },
      { name: "Lentilha", amount: "½ xícara" },
      { name: "Cenoura", amount: "1 pequena" },
      { name: "Abobrinha", amount: "½ unidade" },
    ],
    macros: { calories: 350, protein: 16, carbs: 55, fat: 6 },
    tags: ["lunch"],
    prepTime: 30,
    difficulty: "easy",
    servings: 1,
  },
  {
    name: "Filé Mignon com Purê de Batata",
    description: "Filé mignon grelhado com purê leve e salada verde",
    ingredients: [
      { name: "Filé mignon", amount: "120g" },
      { name: "Batata", amount: "1 média" },
      { name: "Leite desnatado", amount: "50ml" },
      { name: "Mix de folhas", amount: "1 xícara" },
    ],
    macros: { calories: 420, protein: 35, carbs: 35, fat: 15 },
    tags: ["lunch", "dinner"],
    prepTime: 30,
    difficulty: "medium",
    servings: 1,
  },
  {
    name: "Nhoque de Batata Doce",
    description: "Nhoque de batata doce com molho de tomate caseiro",
    ingredients: [
      { name: "Batata doce", amount: "200g" },
      { name: "Farinha de arroz", amount: "3 colheres" },
      { name: "Ovo", amount: "1 unidade" },
      { name: "Molho de tomate", amount: "½ xícara" },
    ],
    macros: { calories: 360, protein: 12, carbs: 58, fat: 8 },
    tags: ["lunch"],
    prepTime: 35,
    difficulty: "hard",
    servings: 1,
  },
  {
    name: "Carne de Panela com Mandioca",
    description: "Carne cozida lentamente com mandioca e cenoura",
    ingredients: [
      { name: "Acém", amount: "150g" },
      { name: "Mandioca", amount: "100g" },
      { name: "Cenoura", amount: "1 unidade" },
    ],
    macros: { calories: 440, protein: 32, carbs: 42, fat: 16 },
    tags: ["lunch"],
    prepTime: 60,
    difficulty: "medium",
    servings: 1,
  },
  {
    name: "Yakisoba de Frango",
    description: "Macarrão oriental com frango e vegetais salteados",
    ingredients: [
      { name: "Macarrão para yakisoba", amount: "100g" },
      { name: "Frango em tiras", amount: "100g" },
      { name: "Brócolis", amount: "½ xícara" },
      { name: "Cenoura", amount: "½ unidade" },
      { name: "Shoyu", amount: "2 colheres" },
    ],
    macros: { calories: 410, protein: 28, carbs: 48, fat: 12 },
    tags: ["lunch", "dinner"],
    prepTime: 20,
    difficulty: "medium",
    servings: 1,
  },
  {
    name: "Bolinho de Grão-de-Bico (Falafel)",
    description: "Falafel assado com salada e molho tahine",
    ingredients: [
      { name: "Grão-de-bico cozido", amount: "1 xícara" },
      { name: "Cebola", amount: "¼ unidade" },
      { name: "Salsinha", amount: "2 colheres" },
      { name: "Tahine", amount: "1 colher" },
    ],
    macros: { calories: 320, protein: 14, carbs: 40, fat: 12 },
    tags: ["lunch", "snack"],
    prepTime: 25,
    difficulty: "medium",
    servings: 1,
  },

  // --- Jantar (10) ---
  {
    name: "Sopa de Legumes com Frango",
    description: "Sopa reconfortante com legumes variados e frango desfiado",
    ingredients: [
      { name: "Frango", amount: "100g" },
      { name: "Cenoura", amount: "1 unidade" },
      { name: "Abobrinha", amount: "1 unidade" },
      { name: "Batata", amount: "1 pequena" },
    ],
    macros: { calories: 280, protein: 24, carbs: 30, fat: 6 },
    tags: ["dinner"],
    prepTime: 30,
    difficulty: "easy",
    servings: 1,
  },
  {
    name: "Omelete Recheada de Legumes",
    description: "Omelete com abobrinha, tomate e queijo",
    ingredients: [
      { name: "Ovo", amount: "3 unidades" },
      { name: "Abobrinha", amount: "½ unidade" },
      { name: "Tomate", amount: "1 pequeno" },
      { name: "Queijo minas", amount: "30g" },
    ],
    macros: { calories: 300, protein: 24, carbs: 8, fat: 20 },
    tags: ["dinner"],
    prepTime: 12,
    difficulty: "easy",
    servings: 1,
  },
  {
    name: "Salada de Quinoa com Camarão",
    description: "Salada morna de quinoa com camarão e abacate",
    ingredients: [
      { name: "Quinoa", amount: "½ xícara" },
      { name: "Camarão", amount: "100g" },
      { name: "Abacate", amount: "¼ unidade" },
      { name: "Tomate cereja", amount: "5 unidades" },
    ],
    macros: { calories: 380, protein: 28, carbs: 32, fat: 16 },
    tags: ["dinner"],
    prepTime: 20,
    difficulty: "medium",
    servings: 1,
  },
  {
    name: "Peixe Assado com Legumes",
    description: "Tilápia assada com abobrinha, cenoura e cebola",
    ingredients: [
      { name: "Tilápia", amount: "150g" },
      { name: "Abobrinha", amount: "1 unidade" },
      { name: "Cenoura", amount: "1 unidade" },
      { name: "Azeite", amount: "1 colher" },
    ],
    macros: { calories: 300, protein: 32, carbs: 18, fat: 12 },
    tags: ["dinner"],
    prepTime: 25,
    difficulty: "easy",
    servings: 1,
  },
  {
    name: "Creme de Abóbora com Gengibre",
    description: "Sopa cremosa de abóbora com gengibre e croutons",
    ingredients: [
      { name: "Abóbora", amount: "300g" },
      { name: "Gengibre", amount: "1 pedaço" },
      { name: "Cebola", amount: "½ unidade" },
      { name: "Creme de leite light", amount: "2 colheres" },
    ],
    macros: { calories: 200, protein: 6, carbs: 32, fat: 6 },
    tags: ["dinner"],
    prepTime: 25,
    difficulty: "easy",
    servings: 1,
  },
  {
    name: "Frango ao Curry com Arroz",
    description: "Frango em molho curry com arroz basmati",
    ingredients: [
      { name: "Peito de frango", amount: "120g" },
      { name: "Curry em pó", amount: "1 colher chá" },
      { name: "Leite de coco", amount: "50ml" },
      { name: "Arroz basmati", amount: "½ xícara" },
    ],
    macros: { calories: 400, protein: 32, carbs: 40, fat: 14 },
    tags: ["dinner"],
    prepTime: 25,
    difficulty: "medium",
    servings: 1,
  },
  {
    name: "Hambúrguer Caseiro de Frango",
    description: "Hambúrguer de frango com salada no pão integral",
    ingredients: [
      { name: "Peito de frango moído", amount: "120g" },
      { name: "Pão integral", amount: "1 unidade" },
      { name: "Alface", amount: "2 folhas" },
      { name: "Tomate", amount: "2 fatias" },
    ],
    macros: { calories: 360, protein: 30, carbs: 32, fat: 12 },
    tags: ["dinner"],
    prepTime: 20,
    difficulty: "easy",
    servings: 1,
  },
  {
    name: "Risoto de Cogumelos",
    description: "Risoto cremoso com mix de cogumelos",
    ingredients: [
      { name: "Arroz arbóreo", amount: "½ xícara" },
      { name: "Mix de cogumelos", amount: "100g" },
      { name: "Caldo de legumes", amount: "300ml" },
      { name: "Parmesão", amount: "20g" },
    ],
    macros: { calories: 380, protein: 14, carbs: 52, fat: 12 },
    tags: ["dinner"],
    prepTime: 30,
    difficulty: "medium",
    servings: 1,
  },
  {
    name: "Tacos de Peixe",
    description: "Tortilhas com peixe grelhado, repolho e limão",
    ingredients: [
      { name: "Peixe branco", amount: "120g" },
      { name: "Tortilha de milho", amount: "2 unidades" },
      { name: "Repolho roxo", amount: "½ xícara" },
      { name: "Limão", amount: "1 unidade" },
    ],
    macros: { calories: 320, protein: 26, carbs: 30, fat: 10 },
    tags: ["dinner"],
    prepTime: 15,
    difficulty: "easy",
    servings: 1,
  },
  {
    name: "Berinjela Recheada",
    description: "Berinjela assada recheada com carne moída e queijo",
    ingredients: [
      { name: "Berinjela", amount: "1 grande" },
      { name: "Carne moída", amount: "80g" },
      { name: "Molho de tomate", amount: "3 colheres" },
      { name: "Queijo mussarela", amount: "30g" },
    ],
    macros: { calories: 300, protein: 22, carbs: 18, fat: 16 },
    tags: ["dinner"],
    prepTime: 35,
    difficulty: "medium",
    servings: 1,
  },

  // --- Lanche (10) ---
  {
    name: "Mix de Castanhas",
    description: "Mix de castanha-do-pará, amêndoas e nozes",
    ingredients: [
      { name: "Castanha-do-pará", amount: "3 unidades" },
      { name: "Amêndoas", amount: "10 unidades" },
      { name: "Nozes", amount: "5 unidades" },
    ],
    macros: { calories: 200, protein: 6, carbs: 6, fat: 18 },
    tags: ["snack"],
    prepTime: 1,
    difficulty: "easy",
    servings: 1,
  },
  {
    name: "Banana com Pasta de Amendoim",
    description: "Banana fatiada com pasta de amendoim integral",
    ingredients: [
      { name: "Banana", amount: "1 unidade" },
      { name: "Pasta de amendoim", amount: "1 colher" },
    ],
    macros: { calories: 220, protein: 7, carbs: 28, fat: 10 },
    tags: ["snack", "post_workout"],
    prepTime: 2,
    difficulty: "easy",
    servings: 1,
  },
  {
    name: "Palitos de Cenoura com Homus",
    description: "Cenoura em palitos com homus caseiro",
    ingredients: [
      { name: "Cenoura", amount: "2 unidades" },
      { name: "Homus", amount: "3 colheres" },
    ],
    macros: { calories: 150, protein: 6, carbs: 18, fat: 6 },
    tags: ["snack"],
    prepTime: 5,
    difficulty: "easy",
    servings: 1,
  },
  {
    name: "Bolo de Caneca de Banana",
    description: "Bolo fit de microondas com banana e aveia",
    ingredients: [
      { name: "Banana", amount: "1 unidade" },
      { name: "Ovo", amount: "1 unidade" },
      { name: "Aveia", amount: "2 colheres" },
      { name: "Canela", amount: "a gosto" },
    ],
    macros: { calories: 200, protein: 10, carbs: 28, fat: 6 },
    tags: ["snack"],
    prepTime: 5,
    difficulty: "easy",
    servings: 1,
  },
  {
    name: "Torrada com Ricota e Mel",
    description: "Torrada integral com ricota e fio de mel",
    ingredients: [
      { name: "Torrada integral", amount: "2 unidades" },
      { name: "Ricota", amount: "2 colheres" },
      { name: "Mel", amount: "1 colher chá" },
    ],
    macros: { calories: 180, protein: 8, carbs: 24, fat: 6 },
    tags: ["snack"],
    prepTime: 3,
    difficulty: "easy",
    servings: 1,
  },
  {
    name: "Vitamina de Mamão e Aveia",
    description: "Vitamina com mamão, aveia e leite desnatado",
    ingredients: [
      { name: "Mamão", amount: "1 fatia" },
      { name: "Aveia", amount: "2 colheres" },
      { name: "Leite desnatado", amount: "200ml" },
    ],
    macros: { calories: 200, protein: 8, carbs: 34, fat: 4 },
    tags: ["snack"],
    prepTime: 5,
    difficulty: "easy",
    servings: 1,
  },
  {
    name: "Pipoca Natural",
    description: "Pipoca estourada em panela com pouco óleo e sal",
    ingredients: [
      { name: "Milho de pipoca", amount: "3 colheres" },
      { name: "Óleo de coco", amount: "1 colher chá" },
      { name: "Sal", amount: "pitada" },
    ],
    macros: { calories: 120, protein: 4, carbs: 22, fat: 4 },
    tags: ["snack"],
    prepTime: 5,
    difficulty: "easy",
    servings: 1,
  },
  {
    name: "Ovo Cozido com Sal e Pimenta",
    description: "Ovos cozidos como lanche rápido e proteico",
    ingredients: [
      { name: "Ovo", amount: "2 unidades" },
      { name: "Sal", amount: "a gosto" },
      { name: "Pimenta-do-reino", amount: "a gosto" },
    ],
    macros: { calories: 140, protein: 12, carbs: 1, fat: 10 },
    tags: ["snack"],
    prepTime: 10,
    difficulty: "easy",
    servings: 1,
  },
  {
    name: "Brownie Fit de Batata Doce",
    description: "Brownie de batata doce, cacau e aveia sem açúcar",
    ingredients: [
      { name: "Batata doce cozida", amount: "100g" },
      { name: "Cacau em pó", amount: "2 colheres" },
      { name: "Aveia", amount: "3 colheres" },
      { name: "Ovo", amount: "1 unidade" },
    ],
    macros: { calories: 180, protein: 8, carbs: 26, fat: 6 },
    tags: ["snack"],
    prepTime: 25,
    difficulty: "medium",
    servings: 4,
  },
  {
    name: "Frozen de Banana",
    description: "Sorvete de banana congelada batida no liquidificador",
    ingredients: [
      { name: "Banana congelada", amount: "2 unidades" },
      { name: "Cacau em pó", amount: "1 colher" },
    ],
    macros: { calories: 190, protein: 3, carbs: 42, fat: 2 },
    tags: ["snack"],
    prepTime: 5,
    difficulty: "easy",
    servings: 1,
  },

  // --- Pós-Treino (5) ---
  {
    name: "Shake Proteico de Whey com Banana",
    description: "Shake pós-treino com whey, banana e leite",
    ingredients: [
      { name: "Whey protein", amount: "1 scoop" },
      { name: "Banana", amount: "1 unidade" },
      { name: "Leite", amount: "250ml" },
    ],
    macros: { calories: 350, protein: 32, carbs: 40, fat: 6 },
    tags: ["post_workout"],
    prepTime: 3,
    difficulty: "easy",
    servings: 1,
  },
  {
    name: "Batata Doce com Frango Desfiado",
    description: "Batata doce assada com frango desfiado temperado",
    ingredients: [
      { name: "Batata doce", amount: "1 média" },
      { name: "Frango desfiado", amount: "100g" },
      { name: "Azeite", amount: "1 colher" },
    ],
    macros: { calories: 380, protein: 30, carbs: 42, fat: 10 },
    tags: ["post_workout", "lunch"],
    prepTime: 20,
    difficulty: "easy",
    servings: 1,
  },
  {
    name: "Sanduíche de Atum Integral",
    description: "Sanduíche pós-treino com atum e vegetais",
    ingredients: [
      { name: "Pão integral", amount: "2 fatias" },
      { name: "Atum em água", amount: "1 lata" },
      { name: "Alface", amount: "2 folhas" },
      { name: "Tomate", amount: "3 fatias" },
    ],
    macros: { calories: 320, protein: 30, carbs: 32, fat: 8 },
    tags: ["post_workout"],
    prepTime: 5,
    difficulty: "easy",
    servings: 1,
  },
  {
    name: "Ovos Mexidos com Pão e Abacate",
    description: "Ovos mexidos com torrada e fatias de abacate",
    ingredients: [
      { name: "Ovo", amount: "3 unidades" },
      { name: "Pão integral", amount: "1 fatia" },
      { name: "Abacate", amount: "¼ unidade" },
    ],
    macros: { calories: 380, protein: 22, carbs: 22, fat: 24 },
    tags: ["post_workout"],
    prepTime: 8,
    difficulty: "easy",
    servings: 1,
  },
  {
    name: "Tigela de Açaí Proteica",
    description: "Açaí com whey, granola e frutas para recuperação",
    ingredients: [
      { name: "Polpa de açaí", amount: "200ml" },
      { name: "Whey protein", amount: "½ scoop" },
      { name: "Granola", amount: "30g" },
      { name: "Morango", amount: "5 unidades" },
    ],
    macros: { calories: 400, protein: 20, carbs: 55, fat: 12 },
    tags: ["post_workout", "snack"],
    prepTime: 5,
    difficulty: "easy",
    servings: 1,
  },
];

async function seed() {
  const uri = process.env.MONGODB_URI;
  if (!uri) {
    console.error("MONGODB_URI is required");
    process.exit(1);
  }

  await mongoose.connect(uri);
  console.log("Connected to MongoDB");

  const count = await Recipe.countDocuments();
  if (count > 0) {
    console.log(`Already ${count} recipes in database, skipping seed`);
    await mongoose.disconnect();
    return;
  }

  await Recipe.insertMany(recipes);
  console.log(`Seeded ${recipes.length} Brazilian recipes`);
  await mongoose.disconnect();
}

seed().catch((err) => {
  console.error("Seed failed:", err);
  process.exit(1);
});
